openapi: 3.0.0
info:
  title: My API
  description: This is a simple API
  version: 1.0.0
servers:
  - url: http://localhost:3001

components:
  securitySchemes:
    bearerAuth:            # Nombre del esquema de seguridad
      type: http
      scheme: bearer
      bearerFormat: JWT    # Esto es opcional, pero describe el formato esperado del token

security:
  - bearerAuth: []         # Aplica este esquema de seguridad globalmente, si se necesita

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - age
                - email
                - password
                - role
              properties:
                name:
                  type: string
                age:
                  type: number
                email:
                  type: string
                  format: email
                password:
                  type: string
                role:
                  type: string
                  enum: [Admin, Manager, Employee]
      responses:
        201:
          description: User registered successfully
        400:
          description: User already exists

  /api/employees:
    get:
      summary: Get all employees
      tags:
        - Employees
      security:
        - bearerAuth: []   # Indica que esta ruta requiere autenticación
      responses:
        200:
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: The employee ID
                    name:
                      type: string
                      description: The name of the employee
                    age:
                      type: number
                      description: The age of the employee
                    email:
                      type: string
                      description: The email of the employee
                    role:
                      type: string
                      description: The role of the employee
                      enum: [Admin, Manager, Employee]
        401:
          description: Unauthorized
        403:
          description: Forbidden
